name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Configure Maven
      run: cp .m2/settings.xml $HOME/.m2/settings.xml
    - name: Build with Maven
      run: |
            cd spring-boot-app
            mvn -B package --file pom.xml
    - name: Publish to Azure Artifacts
      run: |
            cd spring-boot-app
            mvn deploy
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.AZURE_DEV_TOKEN }}
       
      

    # - name: Push artifact to repo
    #   uses: actions/upload-artifact@v4
    #   with:
    #      name: Java-maven-artifact
    #      path: spring-boot-app/target/spring-boot-web.jar
         

    
